---
key: igmc_64
model:
  type: IGMC
  hop: 1
  num_relations: 6
  latent_dims:
    - 32
    - 32
    - 32
    - 32
  edge_dropout: 0.

dataset:
  max_seq: 64
#   name: amazon_clothing

train:
  device: 0
  epochs: 20
  batch_size: 128
  learning_rates:
    - 1e-4
    - 2e-3
    - 5e-4
  weight_decay: 0.0
  lr_decay_step: 5
  lr_decay_factor: 0.98
  log_interval: 100
  log_dir: log
