---
key: igmc_128
model:
  type: IGMC
  hop: 1
  num_relations: 6
  latent_dims:
    - 32
    - 32
    - 32
    - 32
  edge_dropout: 0.

dataset:
  max_seq: 64
  name: ml-100k

train:
  device: 0
  epochs: 80
  batch_size: 256
  learning_rates:
    - 1e-4
    # - 2e-3
    # - 5e-4
  weight_decay: 0.0
  lr_decay_step: 5
  lr_decay_factor: 0.98
  log_interval: 100
  log_dir: log
